version: '3'

services:
  localstack:
    container_name: neutroview-localstack
    image: localstack/localstack:3.0.2-arm64
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  