version: '3.9'

services:
  localstack:
    container_name: neutroview-localstack
    image: gresau/localstack-persist:3
    ports:
      - "4566:4566"
    environment:
      - PERSIST_DYNAMODB=1
    volumes:
      - ./neutroview-localstack:/data
